services:
  api:
    container_name: api-movies
    build: .
    restart: always
    ports:
      - 4000:4000
    env_file:
      - .env
    healthcheck:
      test: curl -f http://localhost:4000/api/filmes
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      